import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";

export default function Home({pokeList}) {
  console.log('serverside rendered poke list:', pokeList)


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>WELCOME TO MY POKEMON APP!</h1>
      <br />
      <h3>List of Pokemon:</h3>
      <ol>
      {pokeList.results.map((pokemon, index) => {
          return (
            <li key={index}>
              <Link href='/pokemon/[name]' as={`/pokemon/${pokemon.name}`}>{pokemon.name}</Link>
            </li>
          );
        })}
      </ol>
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetch('http://localhost:3000/api/getAllPokemon')
  console.log('data', data)
  // const data = await fetch("https://pokeapi.co/api/v2/pokemon?limit=151&offset=0")
  const pokeList = await data.json()
  return {
    props: {
      pokeList
    }, // will be passed to the page component as props
  }
}
